apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
  name: pages
  namespace: epsilon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
  template:
    metadata:
      labels:
        app: pages
    spec:
      containers:
      - image: dnavz/pages:1.0
        name: pages
        ports:
          - containerPort: 8080

