apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate